// .effective/exceptions.ts
// Generated by `npx effective init` on 2026-05-12.
// Add project-specific exception instances below `seeds.builtInExceptions`.

import { defineExceptions, seeds } from 'effective';

export default defineExceptions({
  // Built-in templates: CLI fatal-exit, external library drift defense,
  // type narrowing of impossible, TTY-bound paths, Zod internal
  // introspection, and others. See schemas/builtin.ts for the full list.
  ...seeds.builtInExceptions,

  // Project-specific exceptions go here. Each needs a category, mechanism,
  // context, retirementCondition, and addedDate.
  // Example:
  //   'our-postgres-driver-quirk': {
  //     id: 'our-postgres-driver-quirk',
  //     category: 'external-library-drift-defense',
  //     mechanism: 'ts-expect-error',
  //     context: 'pg@8.x leaves stale connections under specific error shapes',
  //     retirementCondition: 'Resolved when we migrate to pg@9 or postgres.js',
  //     addedDate: '2026-05-12',
  //     status: 'active',
  //   },
});
